config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get "pages/home", to: "pages#home"

    resources :recipes do
        resources :comments, only: [:create]
        member do 
          post 'like'
        end
      end

    get "/signup", to: "chefs#new"
    resources :chefs, except: [:new]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => "/cable"
    get "/chat", to: "chatrooms#show"

    resources :messages, only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5, maximum: 500 }
    validates :chef_id, presence: true
    belongs_to :chef
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments, dependent: :destroy
    has_one_attached :image
    has_many :likes, dependent: :destroy

    def thumbs_up_total
        self.likes.where(like: true).size
    end
      
    def thumbs_down_total
        self.likes.where(like: false).size    
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
    before_action :require_user, except: [:index, :show, :like]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_user_like, only: [:like]
    
    
    def index
        @recipes = Recipe.page(params[:page]).per(2)
    end
    
    def show
        @comment = Comment.new
        @comments = @recipe.comments.page(params[:page]).per(3)
    end
    
    def new
      @recipe = Recipe.new
    end
    
    def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef = current_chef
      if @recipe.save
        flash[:success] = "Recipe was created successfully!"
        redirect_to recipe_path(@recipe)
      else
        render 'new'
      end
    end
    
    def edit
      
    end
    
    def update
      if @recipe.update(recipe_params)
        flash[:success] = "Recipe was updated successfully!"
        redirect_to recipe_path(@recipe)
      else
        render 'edit'
      end
    end
    
    def destroy
      Recipe.find(params[:id]).destroy
      flash[:success] = "Recipe deleted successfully"
      redirect_to recipes_path
    end
    
    def like
        like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
        if like.valid?
          flash[:success] = "Your selection was succesful"
          redirect_back(fallback_location: root_path)
        else
          flash[:danger] = "You can only like/dislike a recipe once"
          redirect_back(fallback_location: root_path)
        end
    end

    private
    
      def set_recipe
        @recipe = Recipe.find(params[:id])
      end
    
      def recipe_params
        params.require(:recipe).permit(:name, :description, :image, ingredient_ids: [])
      end
      
      def require_same_user
        if current_chef != @recipe.chef and !current_chef.admin?
          flash[:danger] = "You can only edit or delete your own recipes"
          redirect_to recipes_path
        end  
      end

      def require_user_like
        if !logged_in?
          flash[:danger] = "You must be logged in to perform that action"
          redirect_to :back
        end
      end
  end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe%>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-12">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-12">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label "Selecciona una foto" %>
        </div>
        <div class="col-md-12">
          <%= f.file_field :image %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
            </div>
        </div>
      </div>
      <div class="form-group center">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
      </div>
    <% end %>
    <div class="colormatch center">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<ul class="list-group list-group-flush">
<% obj.each do |recipe| %>

  <li class="list-group-item">
    <div class="row center">
        <section class="center">

            <%= gravatar_for(recipe.chef, size:120) %>
        </section>
        <div class="cold-md-8 well">
            <h4><%=link_to recipe.name, recipe_path(recipe) %></h4>
            <p><%= truncate(recipe.description, length: 150) %></p>

             <% if recipe.image.attached? %>
                <%= image_tag url_for(recipe.image), class: "center" %> 
            <% end %>
            <% if recipe.ingredients.any? %>
                <p> Ingredients: <%= render recipe.ingredients %> </p> 
            <% end %>

            <p>
                <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by 
                            <%= recipe.chef.chefname.capitalize %> | <%= pluralize(recipe.comments.count, "Comment") %> </small></span>
            </p>
            <p class="center">
                <%= link_to like_recipe_path(recipe, like: true), method: :post, class: "link" do %>
                <i class="fa-solid fa-thumbs-up fa-2xl margin20px"></i>
                <% end %>    
                <%= link_to like_recipe_path(recipe, like: false), method: :post, class: "link" do %>
                <i class="fa-solid fa-thumbs-down fa-2xl margin20px"></i>
                <% end %>
            </p>
            <p>
             <span class="margin25px"><%= recipe.thumbs_up_total %></span><span class="margin25px"><%= recipe.thumbs_down_total %></span>
            </p> 
            <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
                <div class="recipe-actions">
                    <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
                    <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete,
                                            data: {confirm: "Are you sure you want to delete this recipe?"},
                                            class: "btn btn-xs btn-danger" %>
                </div>
            <% end %>
        </div>
    </div>
    
<% end %>
</li>
</ul>

app/views/recipes/edit.html.erb
<%= render "shared/page_title", title: "Edit a recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render "shared/page_title", title: "Listing recipes" %>
<div class="center">
<%= paginate @recipes, window: 2, class: "center"%>
</div>
<%= render "recipe", obj: @recipes %>

app/views/recipes/new.html.erb
<%= render "shared/page_title", title: "Create a new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>
<div class="card well">
  <div class="card-body">
    <h4 class="center description"><strong>Steps: </strong></h4>
    <hr/>
    <div class="center">
    <%= simple_format(@recipe.description) %>
    <% if @recipe.image.attached? %>
        <%= image_tag url_for(@recipe.image), class: "center" %> 
    <% end %>
    <% if @recipe.ingredients.any? %>
        <p>Ingredients: <%= render @recipe.ingredients %></p>
    <% end %>
    </div>
    <hr/>
    <div class="text-rigth">
        <p class="center"><em>Created by: </em></p>
        <p class="center">
            <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
        </p>
        <p class="center">
            <small><%= @recipe.chef.chefname.capitalize %></small>
        </p>

        <p class="center">
            <%= link_to like_recipe_path(@recipe, like: true), method: :post, class: "link" do %>
            <i class="fa-solid fa-thumbs-up"></i>
            <% end %> <%= @recipe.thumbs_up_total %> || 
            <%= link_to like_recipe_path(@recipe, like: false), method: :post, class: "link" do %>
            <i class="fa-solid fa-thumbs-down"></i><%= @recipe.thumbs_down_total %>
            <% end %>
        </p>
    </div>
    <p>
        <div class="text-right">Created <%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
  <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin) %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
    <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                            data: {confirm: "Are you sure you want to delete this recipe?"},
                                            class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to recipe listing", recipes_path, class: "btn btn-xs btn-primary" %>
  </div>
</div>

<% if logged_in? %>
    <div class="row">
    <div class="col-md-18 col-md-offset-2">
        <h3>Comments: </h3><hr/>
        <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
            </div>
            <div class="col-md-12">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter comment here" %>
            </div>
        </div>
        <div class="form-group center">
            <%= f.submit "Submit comment", class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
        <% end %>
    </div>
    </div>
<% end %>

<% if @recipe.comments.count != 0 %>
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
  </div>
<% else %>
      <h3>No Comments Yet!</h3>
<% end %>