config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get "pages/home", to: "pages#home"

    resources :recipes do
        resources :comments, only: [:create]
        member do 
          post 'like'
        end
      end

    get "/signup", to: "chefs#new"
    resources :chefs, except: [:new]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => "/cable"
    get "/chat", to: "chatrooms#show"

    resources :messages, only: [:create]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :set_ingredient, only: [:edit, :update, :show]
    before_action :require_admin, except: [:show, :index]
    
    def new
      @ingredient = Ingredient.new
    end
    
    def create
      @ingredient = Ingredient.new(ingredient_params)
      if @ingredient.save
        flash[:success] = "Ingredient was successfully created"
        redirect_to ingredient_path(@ingredient)
      else
        render 'new'
      end
    end
    
    def edit
      
    end
    
    def update
      if @ingredient.update(ingredient_params)
        flash[:success] = "Ingredient name was updated successfully"
        redirect_to @ingredient
      else
        render 'edit'
      end
    end
    
    def show
      @ingredient_recipes = @ingredient.recipes.page(params[:page]).per(2)
    end
    
    def index
        @ingredients = Ingredient.page(params[:page]).per(3)
    end
    
    private
    
    def ingredient_params
        params.require(:ingredient).permit(:name, :description, ingredient_ids: [])
    end

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end
    
    def require_admin
        if !logged_in? || (logged_in? and !current_chef.admin?)
            flash[:danger] = "Only admin users can perform that action"
            redirect_to ingredients_path
        end
    end
end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient%>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-12">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>
      </div>
      <div class="form-group center">
          <%= f.submit(@ingredient.new_record? ? "Add new ingredient" : "Update ingredient",
                                             class: "btn btn-xlarge btn-primary btn-lg ") %>
      </div>
    <% end %>
    <div class="colormatch center">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge bg-secondary"><%= link_to ingredient.name, ingredient_path(ingredient)%></span>

app/views/ingredients/edit.html.erb
<%= render "shared/page_title", title: "Edit ingredient name" %>
<%= render "form" %>

app/views/ingredients/index.html.erb
<%= render "shared/page_title", title: "Available ingredients" %>
<%= paginate @ingredients%>
<div class="center list-group">
  <% @ingredients.each do |ing| %>
    <ul class="list-group-item listing">
      <div class="row">
        <div class="col">
            <li class="chef-title"><%= link_to ing.name.capitalize, 
                                         ingredient_path(ing) %></li>
            <li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>
            <% if logged_in? && current_chef.admin?%>
                <li class="chef-title"> <%= link_to "Edit this ingredient", edit_ingredient_path(ing) %> </li>
            <% end %>
        </div>
      </div>
    </ul>      
  <% end %>
</div>

app/views/ingredients/new.html.erb
<%= render "shared/page_title", title: "Enter a new ingredient" %>
<%= render "form" %>

app/views/ingredients/show.html.erb
<%= render "shared/page_title", title: "#{@ingredient.name}" %>

<% if @ingredient.recipes.count != 0%>
    <h2 class="text-center">Recetas con <%= @ingredient.name %></h2>

    <%= paginate @ingredient_recipes%>
    <%= render "recipes/recipe", obj: @ingredient_recipes %>
<% else %>
    <h4 class="text-center">No hay recetas con este ingrediente</h4>
<% end %>