config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get "pages/home", to: "pages#home"

    resources :recipes do
        resources :comments, only: [:create]
        member do 
          post 'like'
        end
      end

    get "/signup", to: "chefs#new"
    resources :chefs, except: [:new]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => "/cable"
    get "/chat", to: "chatrooms#show"

    resources :messages, only: [:create]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-success" role="alert">
        <%= msg %>
        <a href="#" class="close" data-dismiss="alert">×</a>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
  <div class="container-fluid">
    <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
        <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Recipe list", recipes_path, class: "nav-link" %>
        </li>
        <% if logged_in?%>
        <li class="nav-item">
        <%= link_to "Create new recipe", new_recipe_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "ChefChat", chat_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
        <%= link_to "Chefs", chefs_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ingredients
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Available ingredients", 
                                    ingredients_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
             <% Ingredient.all.each do |ingredient| %>
                <li><%= link_to ingredient.name.capitalize, 
                                    ingredient_path(ingredient), class: "dropdown-item" %></li>
            <% end %>
            <% if logged_in? && current_chef.admin? %>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Create ingredient", new_ingredient_path, class: "dropdown-item"%></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <% if !logged_in?%>
        <li class="nav-item">
        <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <%else%>
        <li class="nav-item">
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2c5d84754f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>